# Author: Rosé Pine <hi@rosepinetheme.com>
# Upstream: https://github.com/rose-pine/helix
# Contributing:
#   Please submit changes to https://github.com/rose-pine/helix.
#   The Rosé Pine team will update Helix, including you as a co-author.

"ui.background" = {}
"ui.background.separator" = { bg = "base" }

"ui.cursor" = { fg = "text", bg = "highlight_high" }
# "ui.cursor.select" = {}
"ui.cursor.match" = { fg = "text", bg = "highlight_med" }
"ui.cursor.primary" = { fg = "text", bg = "muted"}

# "ui.gutter" = {}
# "ui.gutter.selected" = {}

"ui.linenr" = { fg = "muted" }
"ui.linenr.selected" = { fg = "text" }

"ui.statusline" = { fg = "subtle", bg = "term_bg" }
"ui.statusline.inactive" = { fg = "muted", bg = "everforest_bg0" }
"ui.statusline.normal" = { fg = "rose", bg = "rose_10" }
"ui.statusline.insert" = { fg = "foam", bg = "foam_10" }
"ui.statusline.select" = { fg = "iris", bg = "iris_10" }
# "ui.statusline.separator" = {}

"ui.popup" = { bg = "term_bg" }
"ui.popup.info" = { bg = "term_bg" }

"ui.window" = { fg = "subtle", bg = "everforest_bg0" }
"ui.help" = { fg = "subtle", bg = "term_bg" }

"ui.text" = { fg = "everforest_gy0" }
"ui.text.focus" = { bg = "overlay" }
"ui.text.info" = { fg = "subtle" }

"ui.virtual.ruler" = { bg = "overlay" }
"ui.virtual.whitespace" = { fg = "highlight_high" }
"ui.virtual.indent-guide" = { fg = "muted" }
"ui.virtual.inlay-hint" = { fg = "subtle" }

"ui.menu" = { fg = "term_bold", bg = "term_bg" }
"ui.menu.selected" = { fg = "text", bg = "everforest_bg3" }
"ui.menu.scroll" = { fg = "muted", bg = "highlight_med" }

"ui.selection" = { bg = "overlay" }
"ui.selection.primary" = { bg = "highlight_med" }

"ui.cursorline.primary" = { bg = "highlight_low" }
"ui.cursorline.secondary" = { bg = "surface" }

"warning" = "gold"
"error" = "love"
"info" = "foam"
"hint" = "iris"
"debug" = "rose"

"diagnostic" = { underline = { color = "subtle", style = "curl" } }
"diagnostic.hint" = { underline = { color = "iris", style = "curl" } }
"diagnostic.info" = { underline = { color = "foam", style = "curl" } }
"diagnostic.warning" = { underline = { color = "gold", style = "curl" } }
"diagnostic.error" = { underline = { color = "love", style = "curl" } }
"special" = "rose"

"attribute" = "iris"

"type" = "foam"
# "type.builtin" = ""

# "constructor" = "pine_2"
"constructor" = "lavender"

"constant" = "rose" # maybe foam
"constant.builtin" = "gold"
# "constant.builtin.boolean" = ""
"constant.character" = "gold"
"constant.character.escape" = "pine"
"constant.numeric" = "gold"
# "constant.numeric.integer" = ""
# "constant.numeric.float" = ""

"string" = "bronze"
# "string.regexp" = ""
# "string.special" = ""
# "string.special.path" = ""
# "string.special.url" = ""
# "string.special.symbol" = ""

"comment" = { fg = "muted", modifiers = ["italic"]}
# "comment.line" = ""
# "comment.block" = ""
# "comment.block.documentation" = ""

"variable" = "off_white"
"variable.builtin" = "love"
"variable.parameter" = "iris"
# "variable.other" = "lavender"
"variable.other" = "text"
# "variable.other.member" = "lavender"

"label" = "foam"

"punctuation" = "subtle"
# "punctuation.delimiter" = ""
# "punctuation.bracket" = ""
# "punctuation.special" = ""

"keyword" = "pine"
# "keyword.control" = ""
# "keyword.control.conditional" = ""
# "keyword.control.repeat" = ""
# "keyword.control.import" = ""
"keyword.control.return" = "love"
# "keyword.control.exception" = ""
"keyword.operator" = "subtle"
# "keyword.directive" = ""
# "keyword.function" = ""
# "keyword.storage" = ""
# "keyword.storage.type" = ""
# "keyword.storage.modifier" = ""

"operator" = "subtle"

"function" = "rose" # maybe pine
"function.builtin" = "love"
"function.method" = "rose_2"
# "function.macro" = ""
# "function.special" = ""

# "tag" = "foam"
"tag" = "pine"

"namespace" = "iris"

"markup.heading.marker" = "muted"
"markup.heading" = { fg = "iris", modifiers = ["bold"] }
"markup.heading.1" = { fg = "iris", modifiers = ["bold"] }
"markup.heading.2" = { fg = "foam", modifiers = ["bold"] }
"markup.heading.3" = { fg = "rose", modifiers = ["bold"] }
"markup.heading.4" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.5" = { fg = "pine", modifiers = ["bold"] }
"markup.heading.6" = { fg = "foam", modifiers = ["bold"] }
# "markup.heading.completion" = ""
# "markup.heading.hover" = ""
"markup.list" = "muted"
# "markup.list.unnumbered" = ""
# "markup.list.numbered" = ""
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = "iris"
"markup.link.url" = { fg = "iris",  underline = { color = "iris", style = "line" } } 
"markup.link.label" = "subtle"
"markup.link.text" = "text"
"markup.quote" = "subtle"
"markup.raw" = "subtle"
# "markup.raw.inline" = {}
# "markup.raw.inline.completion" = {}
# "markup.raw.inline.hover" = {}
# "markup.raw.block" = {}
# "markup.normal" = ""
# "markup.normal.completion" = ""
# "markup.normal.hover" = ""

"diff" = "overlay"
"diff.plus" = "foam"
"diff.minus" = "love"
"diff.delta" = "highlight_high"
# "diff.delta.moved" = ""

[palette]
base           = "#232136" 
surface        = "#2a273f" 
# surface        = "#2a343b" 
overlay        = "#393552"
muted          = "#6e6a86"
subtle         = "#908caa"
# text           = "#e0def4"
text           = "#c9c7db"
love           = "#eb6f92"
love_10        = "#3a2841"
gold           = "#f6c177"
gold_10        = "#39313e"
bronze         = "#ddad6b"
rose           = "#ea9a97"
rose_2         = "#ebbcba"
rose_10        = "#392d41"
pine           = "#3e8fb0"
pine_2         = "#31748f"
pine_10        = "#252c44"
foam           = "#9ccfd8"
foam_10        = "#2e3248"
iris           = "#c4a7e7"
iris_10        = "#342e4a"
highlight_low  = "#2a283e"
highlight_med  = "#44415a"
highlight_high = "#56526e"
lilac          = "#dbbfef"
lavender       = "#a4a0e8"
# off_white      = "#d1c8b7"
# off_white      = "#d5cdbe"
# off_white      = "#bfb8ab"
off_white      = "#cac3b5"
# off_white      = "#bcb4a4"
term_sel       = "#073642"
term_bold      = "#93a1a1"
ansi_br_black  = "#002b36"
ansi_green     = "#859900"
ansi_cyan      = "#2aa198"
everforest_bg0 = "#2d353b"
everforest_bg1 = "#343f44"
everforest_bg2 = "#3d484d"
everforest_bg3 = "#475258"
everforest_gy0 = "#9da9a0"